'use strict';

/**
 * codexgen.js - generate the Codex wiring files (SPEC section 7, and
 * _dev/reference/codex-wiring.md). Shared by `setup` and `mirror`: both call
 * writeCodexFiles(root) so the wiring always matches the current install path.
 *
 *   .codex/hooks.json  - PreToolUse AND PostToolUse blocks, both pointing at
 *                        the SAME guard script (system/guards/item-hook.js) by
 *                        ABSOLUTE path, same event names + matcher style as
 *                        Claude's wiring. A top-level "description" key carries
 *                        the "generated - do not edit" header. It MUST be
 *                        "description" (the one non-hooks key Codex's strict
 *                        hooks.json parser allows): Codex 0.144.x rejects the
 *                        WHOLE file on any other top-level key (e.g. "_comment"),
 *                        which silently disables every hook under Codex.
 *   .codex/config.toml - the minimal v1 features block (hooks = true), with a
 *                        real TOML "# generated" comment header.
 *   .codex/agents/*.toml - generated from .claude/agents/*.md, with the agent
 *                          body embedded as developer instructions.
 *
 * Both files are written atomically (SPEC section 2), UTF-8, no BOM, LF endings.
 * The absolute path is built with path.join, so it is correct on Windows too;
 * JSON.stringify escapes any backslashes inside the command string.
 */

const path = require('path');
const fs = require('fs');
const { atomicWrite } = require('./atomic.js');

const GENERATED_NOTE = 'GENERATED by growos setup - do not hand-edit.';

/** The absolute path to the guard script this install ships. */
function hookScriptPath(root) {
  return path.join(String(root), 'system', 'guards', 'item-hook.js');
}
/** The absolute path to the session-start reconciler this install ships. */
function sessionStartScriptPath(root) {
  return path.join(String(root), 'system', 'guards', 'session-start.js');
}

/** The command string Codex runs for the item guard: node "<abs path>". */
function hookCommand(root) {
  return 'node "' + hookScriptPath(root) + '"';
}
function sessionStartCommand(root) {
  return 'node "' + sessionStartScriptPath(root) + '"';
}

/**
 * Build the hooks.json object. It mirrors the Claude wiring (SPEC section 4.6):
 *   PreToolUse   — file edits (Write|Edit|MultiEdit|apply_patch) AND Bash.
 *   PostToolUse  — file edits.
 *   SessionStart — the reconciler.
 * (The Claude wiring also has a Read matcher for the .env secrets guard; Codex
 * does not report a "Read" tool — its file reads are shell (`cat`), covered by
 * the Bash guard — so it is intentionally omitted here to keep the trusted-hook
 * set stable.)
 * The matcher includes `apply_patch` because current Codex reports file edits as
 * tool_name "apply_patch"; including it (as well as Write|Edit) covers both how
 * Codex matches (file-edit alias) and a literal tool-name match.
 */
function hooksObject(root) {
  const guard = { type: 'command', command: hookCommand(root), timeout: 10 };
  const bashGuard = { type: 'command', command: hookCommand(root), timeout: 5 };
  const sess = { type: 'command', command: sessionStartCommand(root), timeout: 10 };
  // NOTE: the header MUST live under "description". Codex 0.144.x's hooks.json
  // parser is strict (deny_unknown_fields) and rejects the entire file — turning
  // OFF every hook — on any other top-level key. "_comment" broke it silently.
  return {
    description: GENERATED_NOTE,
    hooks: {
      PreToolUse: [
        { matcher: 'Write|Edit|MultiEdit|apply_patch', hooks: [Object.assign({}, guard)] },
        { matcher: 'Bash', hooks: [Object.assign({}, bashGuard)] },
      ],
      PostToolUse: [
        { matcher: 'Write|Edit|MultiEdit|apply_patch', hooks: [Object.assign({}, guard)] },
      ],
      SessionStart: [
        { matcher: '', hooks: [Object.assign({}, sess)] },
      ],
    },
  };
}

/** The minimal config.toml body (features block only in v1). */
function configToml() {
  return ['# ' + GENERATED_NOTE, '[features]', 'hooks = true', ''].join('\n');
}

function unquoteYamlScalar(value) {
  const s = String(value).trim();
  if (s.length < 2) return s;
  if (s[0] === "'" && s[s.length - 1] === "'") {
    return s.slice(1, -1).replace(/''/g, "'");
  }
  if (s[0] === '"' && s[s.length - 1] === '"') {
    try { return JSON.parse(s); } catch (_) { return s.slice(1, -1); }
  }
  return s;
}

function parseAgentMarkdown(raw, fileName) {
  const normalized = String(raw).replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const match = normalized.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error('.claude/agents/' + fileName + ' has no valid frontmatter block');

  const frontmatter = {};
  for (const line of match[1].split('\n')) {
    const field = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/);
    if (field) frontmatter[field[1]] = unquoteYamlScalar(field[2]);
  }

  return {
    name: frontmatter.name || path.basename(fileName, '.md'),
    description: frontmatter.description || '',
    body: match[2].replace(/^\n+/, '').replace(/\s+$/, ''),
  };
}

function tomlString(value) {
  const s = String(value);
  if (!s.includes("'") && !/[\n\r\u0000-\u001f]/.test(s)) return "'" + s + "'";
  return JSON.stringify(s);
}

function developerInstructions(body) {
  if (!body.includes("'''")) return "'''\n" + body + "\n'''";
  return JSON.stringify(body);
}

function agentToml(agent, fileName) {
  return [
    '# GENERATED from .claude/agents/' + fileName + ' by growos setup - do not hand-edit.',
    'name = ' + JSON.stringify(agent.name),
    'description = ' + tomlString(agent.description),
    'developer_instructions = ' + developerInstructions(agent.body),
    '',
  ].join('\n');
}

/** Regenerate .codex/agents from the canonical .claude/agents markdown files. */
function writeCodexAgents(root) {
  const sourceDir = path.join(String(root), '.claude', 'agents');
  const targetDir = path.join(String(root), '.codex', 'agents');
  fs.mkdirSync(targetDir, { recursive: true });

  let files = [];
  try {
    files = fs.readdirSync(sourceDir).filter((name) => name.endsWith('.md')).sort();
  } catch (_) {
    files = [];
  }

  const desired = new Set();
  for (const fileName of files) {
    const targetName = path.basename(fileName, '.md') + '.toml';
    desired.add(targetName);
    const raw = fs.readFileSync(path.join(sourceDir, fileName), 'utf8');
    const agent = parseAgentMarkdown(raw, fileName);
    atomicWrite(path.join(targetDir, targetName), agentToml(agent, fileName));
  }

  for (const entry of fs.readdirSync(targetDir, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith('.toml') && !desired.has(entry.name)) {
      fs.rmSync(path.join(targetDir, entry.name), { force: true });
    }
  }

  return files.length;
}

/**
 * writeCodexFiles(root) -> { hooksPath, configPath, hookScript, command }
 * Writes .codex/hooks.json and .codex/config.toml. Idempotent: the same install
 * root always yields the same bytes, so setup and mirror can both call it.
 */
function writeCodexFiles(root) {
  const codexDir = path.join(String(root), '.codex');
  const hooksPath = path.join(codexDir, 'hooks.json');
  const configPath = path.join(codexDir, 'config.toml');

  atomicWrite(hooksPath, JSON.stringify(hooksObject(root), null, 2) + '\n');
  atomicWrite(configPath, configToml());
  const agentCount = writeCodexAgents(root);

  return {
    hooksPath,
    configPath,
    hookScript: hookScriptPath(root),
    command: hookCommand(root),
    agentCount,
  };
}

module.exports = {
  writeCodexFiles,
  writeCodexAgents,
  parseAgentMarkdown,
  agentToml,
  hookScriptPath,
  sessionStartScriptPath,
  hookCommand,
  hooksObject,
  configToml,
};
